### ISSUE TITLE
uevent handling

### ISSUE THREAD

**Issue by dwlehman** [rhinstaller/blivet#11]
Add support for monitoring and handling of uevents. It is important to differentiate between deactivation and actual removal.

NOTE: This implies making blivet thread-safe, which is not necessarily trivial.

The operations to support initially are as follows:
* device create
* device destroy
* device resize
* device rename
* format create
* format destroy

Other operations that may not be initially supported:
* format resize
* container device member set changes (vgextend, btrfs add, &c)
* md management (reshaping, failed member, spare management, &c)

We also want to be able to dynamically track active mounts in the system, but I think that will be accomplished through a separate enhancement.

**Comment by dwlehman** [comment]
I just pushed my development branch to uevents-branch so people can see what I'm up to. As of now it's roughly 27 commits ahead of master.

Done:
* make most of blivet thread-safe
* use events instead of udev-settle to finalize create/destroy/&c
  * tested only with partition, disklabel, ext4, swap

TODO:
* general handling of uevents from outside of blivet
  * I have much of this code written but, because it is largely untested, I did not push it

**Comment by dwlehman** [comment]
**Update**

I'm now able to run examples/lvm.py (both as-is and modified to use a single USB flash drive) and examples/factory.py. This covers disklabels, partitions, md, lvm, lvm-on-md, swap, ext4, and xfs.

Recent changes pushed:
* enable event synchronization for container devices (eg: lvm vg, md array) [383b585a]
  * operations on these devices sometimes manifest as events on member devices
* disable event synchronization for files, nodev devices, &c that don't use udev [57a1c1df]
* mostly-working uevent handlers in the devicetree for outside events [1f400dea7d]
  * tested for various operations on lvm and partitions
* add support for event matching requirements for synchronization [76980000]
  * a format, for example, can specify that the event that signals successful creation must contain a specific value of ID_FS_TYPE and any value of ID_FS_UUID in the device info that accompanies the event (as opposed to assuming the next change event on the appropriate block device, regardless of what data is associated with that event, signals successful completion)

Next steps:
* refactor format event synchronization to ensure that failed operations do not cause deadlocks
* clean up and/or refactor DeviceTree._notifyDevice
* explore splitting format create/destroy/setup/teardown into _preCreate/_create/_postCreate &c like StorageDevice does to consolidate the event synchronization code as well as other common code
* figure out how to test this stuff
* expand documentation, both in code and in docs/

**Comment by dwlehman** [comment]
**Update**

Recent changes:
* Split up format create/destroy/setup/teardown so common pre/post code can be shared [a969705]
* Device and Format operations refactored to prevent deadlocks on failure. [4de6118]
* Added unit tests for EventQueue and StorageEventSynchronizer hierarchy [2f22333]
* Split action list management out of DeviceTree into actionlist.ActionList [1b96208]
* Split device discovery out of DeviceTree into discoverer.Discoverer [92e0c01ff]
* Split event handlers out of DeviceTree into handler.EventHandler [416ea9e3]

devicetree.py is much more manageable now that action management and device discovery have been split out into separate modules:

    [david@localhost blivet]$ git show HEAD~5:blivet/devicetree.py | wc -l
    3267
    [david@localhost blivet]$ wc -l blivet/devicetree.py blivet/actionlist.py blivet/discoverer.py blivet/handler.py
      1016 blivet/devicetree.py
       308 blivet/actionlist.py
      1569 blivet/discoverer.py
       590 blivet/handler.py
      3483 total

Next steps:
* Handle changes to devices with scheduled actions
  * cancel all scheduled actions on devices that get changed from outside blivet
* Patch anaconda to detect changes during installation
  * user notification
  * automatic update of data for changed disks
  * enable return to disk selection for new disks

**Comment by dwlehman** [comment]
Design notes: https://github.com/rhinstaller/blivet/wiki/uevent-handling-design-overview

**Comment by vpodzime** [comment]
First of all -- big **THANKS!** for the design notes, they really make things clearer (to me at least). One thing I don't quite understand though is how external changes would be handled during the processActions() call. We need to be listening to udev events in that time for action/operation completion notification, but we can hardly do any updates of the DeviceTree while actions are being processed. Is there some blocking or filtering mechanism for that?

**Comment by dwlehman** [comment]
That's something I haven't addressed yet. It's a small window of time and, to some extent, if users are changing things during that time they are going to have problems. We can be more strict during that time about ignoring unexpected events, but if someone is changing things out from under us while we are trying to work there isn't anything we can do to ensure that things don't go sideways as a result. My sense is that it's mostly going to be covered by a disclaimer along the lines of: changing anything on disks that have blivet actions scheduled is going to result in undefined (and, most likely, undesirable) behavior.

**Comment by dwlehman** [comment]
#311 addressed the major piece of this, which is updating the `DeviceTree` when things are changed from outside of blivet. At some point I will revisit manual synchronization as a replacement for calling `udevadm settle`.
