### ISSUE TITLE
dynamic system mount accounting

### ISSUE THREAD

**Issue by dwlehman** [rhinstaller/blivet#13]
Currently, blivet only looks to the system to see what is mounted when asked to do so. This is not adequate for operation on a running system. Information about system mounts is readily available. What we basically want is a read-only property of FS that consults /proc/mounts (and possibly also /proc/self/mountinfo) on demand to see if/where it is currently mounted. Since this information does not necessarily change rapidly under most circumstances, and this information could be accessed repeatedly for many filesystems, we should seriously consider caching this data and making use of inotify or similar to see when to dump/refresh the cache.

It might be worth talking to @mulkieran about the "tasks" framework she has developed for #12. There is a good chance you can make use of it here.

**Comment by vojtechtrefny** [comment]
https://github.com/rhinstaller/blivet/pull/54 pushed a week ago.
