### ISSUE TITLE
resolveDevice fails on systems with > 15 disks due to bad regex

### ISSUE THREAD

**Issue by bwann** [rhinstaller/blivet#152]
In my Anaconda kickstart config, I'm specifying partition information for 16 disks, sda-sdp. When kickstart calls out to blivet/devicetree.py to look up device mappings for each of the drives, it dies and creates a traceback when resolveDevice(sdp) is being processed.

There's a regex on line 2548 that appears to be the root cause, because the device name contains 'p' it matches this regex and causes blivet to do the wrong thing:

https://github.com/rhinstaller/blivet/blob/rhel7.1-branch/blivet/devicetree.py#L2548 :
```python
  elif re.match(r'(0x)?[A-Za-z0-9]{2}(p\d+)?$', devspec):
```
I'm not exactly sure what this regex is intended to match, (I'm assuming something like "disk1p1") so anchoring it at the beginning may/may not be a trivial fix.

A simple example:
```python
>>> import re
>>> if re.match(r'(0x)?[A-Za-z0-9]{2}(p\d+)?$', 'sdp1'):
...   print "matched"
...
matched
>>> if re.match(r'(0x)?[A-Za-z0-9]{2}(p\d+)?$', 'sdq1'):
...   print "matched"
...
>>>
```

A copy of the Anaconda config+traceback error, storage.log illustrating the problem, are in this gist:
https://gist.github.com/bwann/b8286b72613c03b98ee7  This is from Anaconda 19 with CentOS 7.1, and the regex is the same even in trunk.

**Comment by dwlehman** [comment]
That is for BIOS disk specifications, which are not often used. The regex there is overly inclusive. This should fix it:

```patch
diff --git a/blivet/devicetree.py b/blivet/devicetree.py
index 4b7f476..d6ea40b 100644
--- a/blivet/devicetree.py
+++ b/blivet/devicetree.py
@@ -961,12 +961,13 @@ class DeviceTree(object):
                 (label.startswith("'") and label.endswith("'"))):
                 label = label[1:-1]
             device = self.labels.get(label)
-        elif re.match(r'(0x)?[A-Za-z0-9]{2}(p\d+)?$', devspec):
+        elif re.match(r'(0x)?[A-Fa-f0-9]{2}(p\d+)?$', devspec):
             # BIOS drive number
-            spec = int(devspec, 16)
+            (drive, _p, partnum) = devspec.partition("p")
+            spec = int(drive, 16)
             for (edd_name, edd_number) in edd.edd_dict.items():
                 if edd_number == spec:
-                    device = self.getDeviceByName(edd_name)
+                    device = self.getDeviceByName(edd_name + partnum)
                     break
         elif options and "nodev" in options.split(","):
             device = self.getDeviceByName(devspec)
```

I'll do a pull request for it when I get a chance -- hopefully before the end of the week.

Thanks for reporting it.

**Comment by bwann** [comment]
Thanks!  This looks like it fixes it for me.

**Comment by bwann** [comment]
Did this ever make it in?
