### ISSUE TITLE
add support for cache lvs

### ISSUE THREAD

**Issue by dwlehman** [rhinstaller/blivet#19]
This has several fairly large sub-tasks:
* differentiate between fast and slow media (SSD -v- spinning local disk -v- SAN)
* intelligence in autopart and devicefactory for selecting appropriate disk for cache, swap, fs
* establish a high-level abstraction for cache devices (suitable for bcache as well as dm-cache)

**Comment by vpodzime** [comment]
This was addressed in the PRs #149, #156 and #190 with amendments in PR #199 and #207.
