### ISSUE TITLE
consider using minimal device alignment under some circumstances

### ISSUE THREAD

**Issue by dwlehman** [rhinstaller/blivet#228]
Currently, we align all new partitions according to the optimal alignment info exported by the disk. There is some hardware that exports really large values for the optimal grain size (eg: 64 MiB, but we've also seen 256 MiB). When we get an optimal grain size of 64 MiB we insist on aligning all new partitions on 64 MiB boundaries. The results range from slightly surprising (500MiB->512MiB) to downright problematic (it is impossible to allocate a new PReP partition since its maximum size is 10 MiB).

I'm wondering if we should conditionally fall back to the minimal alignment. The conditions are up for discussion. Some possibilities for when to use the minimal alignment instead of the optimal alignment for new partitions:

1. when the optimal alignment grain is larger than 16 MiB (or other totally arbitrary size)
2. when the optimal alignment grain is larger than the size of the partition currently being allocated
3. when the optimal alignment grain is larger than the size of any of the partitions being allocated

I personally think option 2 is a good choice. That allows small partition allocation on drives reporting large optimal io size, but doesn't affect the other partitions on that drive. It could lead to empty space on the drive, but that doesn't seem like a significant problem.

**Comment by dwlehman** [comment]
Thinking about it a bit more, it occurred to me we could just attempt the optimal alignment, check the size, then fall back to the minimal alignment if there is a problem. Choosing the alignment earlier will be better, though, especially since we have started aligning free regions before choosing one to allocate a new partition from.

**Comment by bcl** [comment]
I like option #2, any arbitrary value we picked for #1 would end up being wrong at some point (eg. I think  I've seen discussions about large nvme device alignments someplace).

**Comment by vpodzime** [comment]
I think we could combine #2 as a proactive approach with what has been suggested by @dwlehman later as a reactive approach. Something tells me there could be problems even when the optimal alignment grain is smaller than the size of the partition.

**Comment by dwlehman** [comment]
I'm planning to remove these properties from `DiskLabel`:

1. `alignment`
2. `endAlignment`

and add these properties:

1. `optimalAlignment`
2. `optimalEndAlignment`
3. `minimalAlignment`
4. `minimalEndAlignment`

and also add a method that returns the appropriate alignment based on a requested partition size. This is where I'm interested in gathering some feedback. I have a basic plan to use a method along the lines of `def getAlignment(self, size=None)`. The question is how to handle the end alignments:

1. add a separate `getEndAlignment` method
2. add a kwarg to `getAlignment`, yielding something like

  `def getAlignment(self, size=None, end=False)`

3. make `getAlignment` return a 2-tuple of (alignment, end_alignment)

Option 1 seems a bit explicit, but it would match the properties. Option 2 seems like it might be trying too hard to avoid adding new methods. Option 3 is nice when you're going to need both alignments, but handling a tuple return value usually looks messy IMO.

Also, I guess if I'm adding a method to get alignment info I don't need those four to be properties, but rather private methods. It will be easy enough to leave something equivalent to the current `alignment`, `endAlignment` for API compatibility where needed.

Opinions?

**Comment by vpodzime** [comment]
I like option 1 the best, it makes things clear and straightforward. Also, we should get rid of those properties, they shouldn't be used from the outside, I think. Removing the need of working with them is the purpose of the ``get[End]Alignment`` methods, isn't it?

**Comment by dwlehman** [comment]
Implemented in #243
