### ISSUE TITLE
move Blivet class into a separate module (blivet.py)

### ISSUE THREAD

**Issue by vpodzime** [rhinstaller/blivet#24]
Having the Blivet class defined in the blivet/__init__.py is bad for many reasons the most itchy one being the fact that if somebody wants to import something small and standalone like "from blivet.arch import isARM", many things that are required by the Blivet class get imported/processed too. Blivet as a module provides many useful functions that are not depending on the Blivet class so it should allow and support their usage without processing all the stuff required by the Blivet class.

The issue is that **this would break the API quite seriously**

**Comment by dwlehman** [comment]
We're about to do the 1.0 release. That might be the perfect time to break API. Once uevents and libblockdev are done and somewhat stable we might go ahead with a 2.0 release, which would be another opportunity to do this.

**Comment by vpodzime** [comment]
patch sent to anaconda-patches

**Comment by vpodzime** [comment]
This has been resolved with the merge of pull #27
