### ISSUE TITLE
move installer-specific functions into a separate module

### ISSUE THREAD

**Issue by dwlehman** [rhinstaller/blivet#25]
Move the following into anaconda since that's the only place they will ever be used:

formats.swap.swapSuggestion
partitioning._scheduleImplicitPartitions
partitioning._schedulePartitions
partitioning._scheduleVolumes
partitioning.doAutoPartition
Blivet.shouldClear
Blivet.clearPartitions
releaseFromRedhatRelease
releaseFromOsRelease
findExistingInstallations
parseFSTab

**Comment by vpodzime** [comment]
A patch sent to the anaconda-patches mailing list with two functions not moved:

* clearPartitions is used by tests to initialize loop devices for testing
* shouldClear is used by clearPartitions and getFreeSpace and could be possibly passed as parameter

**Comment by vpodzime** [comment]
we have decided to take a different approach on this issue. First we want to move all the installation-specific functions into separate modules (osinstall.py and autopart.py) and later move it to anaconda if that seems necessary

**Comment by dwlehman** [comment]
Patch pushed today to move the autopart code into autopart.py and OS installation code into osinstall.py.
