### ISSUE TITLE
Anaconda crashes on f22 and f23 cobbler installation with lvm: Volume group given physical extent size of "4 MiB", but must be one of: 1 KiB

### ISSUE THREAD

**Issue by slavikvin** [rhinstaller/blivet#284]
Here you have validation, at https://github.com/rhinstaller/anaconda/blob/f23-branch/pyanaconda/kickstart.py (1790-1795 lines):

possible_extents = LVMVolumeGroupDevice.get_supported_pe_sizes()
        if pesize not in possible_extents:
            raise KickstartValueError(formatErrorMsg(self.lineno,
                    msg=_("Volume group given physical extent size of \"%(extentSize)s\", but must be one of:\n%(validExtentSizes)s.") %
                         {"extentSize": pesize, "validExtentSizes": ", ".join(str(e) for e in possible_extents)}))

trying to investigate it, i found out that:
from blivet.devices.lvm import LVMVolumeGroupDevice

moving forward, from blivet(https://github.com/rhinstaller/blivet/blob/f23-branch/blivet/devices/lvm.py):
 def get_supported_pe_sizes():
        return [Size(pe_size) for pe_size in blockdev.lvm.get_supported_pe_sizes()]

and blockdev is imported as:

import gi
gi.require_version("BlockDev", "1.0")

from gi.repository import BlockDev as blockdev

when i tried it out, i got something like this:

 >>> from gi.repository import BlockDev
>>> dir(BlockDev)
['BTRFS_MAIN_VOLUME_ID', 'BTRFS_MIN_MEMBER_SIZE', 'BlockDevError', 'BlockDevNotImplementedError', 'BtrfsDeviceInfo', 'BtrfsError', 'BtrfsFilesystemInfo', 'BtrfsSubvolumeInfo', 'CRYPTO_LUKS_METADATA_SIZE', 'CryptoError', 'DMError', 'InitError', 'LVMError', 'LVMLVdata', 'LVMPVdata', 'LVMVGdata', 'LVM_DEFAULT_PE_SIZE', 'LVM_DEFAULT_PE_START', 'LVM_MAX_LV_SIZE', 'LVM_MAX_PE_SIZE', 'LVM_MAX_THPOOL_CHUNK_SIZE', 'LVM_MAX_THPOOL_MD_SIZE', 'LVM_MIN_PE_SIZE', 'LVM_MIN_THPOOL_CHUNK_SIZE', 'LVM_MIN_THPOOL_MD_SIZE', 'LoopError', 'MDDetailData', 'MDError', 'MDExamineData', 'MDRaidError', 'MD_CHUNK_SIZE', 'MD_SUPERBLOCK_SIZE', 'MpathError', 'Plugin', 'PluginSpec', 'SwapError', 'UtilsError', 'UtilsExecError', 'UtilsSizeError', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__file__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__loader__', '__module__', '__name__', '__new__', '__path__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_introspection_module', '_load', '_namespace', '_overrides_module', '_version', 'btrfs', 'btrfs_add_device', 'btrfs_change_label', 'btrfs_check', 'btrfs_create_snapshot', 'btrfs_create_subvolume', 'btrfs_create_volume', 'btrfs_delete_subvolume', 'btrfs_filesystem_info', 'btrfs_get_default_subvolume_id', 'btrfs_list_devices', 'btrfs_list_subvolumes', 'btrfs_mkfs', 'btrfs_remove_device', 'btrfs_repair', 'btrfs_resize', 'btrfs_set_default_subvolume', 'crypto', 'crypto_device_is_luks', 'crypto_escrow_device', 'crypto_generate_backup_passphrase', 'crypto_luks_add_key', 'crypto_luks_change_key', 'crypto_luks_close', 'crypto_luks_format', 'crypto_luks_open', 'crypto_luks_remove_key', 'crypto_luks_resize', 'crypto_luks_status', 'crypto_luks_uuid', 'dm', 'dm_activate_raid_set', 'dm_create_linear', 'dm_deactivate_raid_set', 'dm_get_member_raid_sets', 'dm_get_raid_set_type', 'dm_map_exists', 'dm_name_from_node', 'dm_node_from_name', 'dm_remove', 'func_available', 'get_available_plugin_names', 'init', 'is_initialized', 'is_plugin_available', 'loop', 'loop_get_backing_file', 'loop_get_loop_name', 'loop_setup', 'loop_teardown', 'lvm', 'lvm_get_global_config', 'lvm_get_lv_physical_size', 'lvm_get_max_lv_size', 'lvm_get_supported_pe_sizes', 'lvm_get_thpool_padding', 'lvm_is_supported_pe_size', 'lvm_is_valid_thpool_chunk_size', 'lvm_is_valid_thpool_md_size', 'lvm_lvactivate', 'lvm_lvcreate', 'lvm_lvdeactivate', 'lvm_lvinfo', 'lvm_lvorigin', 'lvm_lvremove', 'lvm_lvresize', 'lvm_lvs', 'lvm_lvsnapshotcreate', 'lvm_lvsnapshotmerge', 'lvm_pvcreate', 'lvm_pvinfo', 'lvm_pvmove', 'lvm_pvremove', 'lvm_pvresize', 'lvm_pvs', 'lvm_pvscan', 'lvm_round_size_to_pe', 'lvm_set_global_config', 'lvm_thlvcreate', 'lvm_thlvpoolname', 'lvm_thpoolcreate', 'lvm_thsnapshotcreate', 'lvm_vgactivate', 'lvm_vgcreate', 'lvm_vgdeactivate', 'lvm_vgextend', 'lvm_vginfo', 'lvm_vgreduce', 'lvm_vgremove', 'lvm_vgs', 'md', 'md_activate', 'md_add', 'md_canonicalize_uuid', 'md_create', 'md_deactivate', 'md_denominate', 'md_destroy', 'md_detail', 'md_examine', 'md_get_md_uuid', 'md_get_superblock_size', 'md_name_from_node', 'md_node_from_name', 'md_nominate', 'md_remove', 'md_run', 'mpath', 'mpath_flush_mpaths', 'mpath_is_mpath_member', 'mpath_set_friendly_names', 'plugin_specs_from_names', 'reinit', 'swap', 'swap_mkswap', 'swap_swapoff', 'swap_swapon', 'swap_swapstatus', 'try_init', 'utils', 'utils_check_util_version', 'utils_exec_and_capture_output', 'utils_exec_and_report_error', 'utils_init_logging', 'utils_size_from_spec', 'utils_size_human_readable', 'utils_version_cmp']
  >>> dir(BlockDev.lvm)
['get_global_config', 'get_lv_physical_size', 'get_max_lv_size', 'get_supported_pe_sizes', 'get_thpool_padding', 'is_supported_pe_size', 'is_valid_thpool_chunk_size', 'is_valid_thpool_md_size', 'lvactivate', 'lvcreate', 'lvdeactivate', 'lvinfo', 'lvorigin', 'lvremove', 'lvresize', 'lvs', 'lvsnapshotcreate', 'lvsnapshotmerge', 'pvcreate', 'pvinfo', 'pvmove', 'pvremove', 'pvresize', 'pvs', 'pvscan', 'round_size_to_pe', 'set_global_config', 'thlvcreate', 'thlvpoolname', 'thpoolcreate', 'thsnapshotcreate', 'vgactivate', 'vgcreate', 'vgdeactivate', 'vgextend', 'vginfo', 'vgreduce', 'vgremove', 'vgs']

BlockDev.lvm.get_supported_pe_sizes()

** (process:32694): CRITICAL **: The function 'bd_lvm_get_supported_pe_sizes' called, but not implemented!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/gi/overrides/BlockDev.py", line 376, in wrapped
    raise self._xrules[e_type].new_exc(msg)
gi.overrides.BlockDev.BlockDevNotImplementedError: The function 'bd_lvm_get_supported_pe_sizes' called, but not implemented!

So, it should be implemented first, or validation based on this function should not used in production stage. If i made some mistakes, please correct me.

Regards, slavikvin.

**Comment by dwlehman** [comment]
It's hard to imagine that user-specified extent size has been broken since F22, but that's what is being reported. @vpodzime, what is your opinion?

**Comment by vojtechtrefny** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1264571

**Comment by vpodzime** [comment]
> It's hard to imagine that user-specified extent size has been broken since F22, but that's what is being reported. @vpodzime, what is your opinion?

It has been, but only on 32bit architectures as explained in the bug @vojtechtrefny added above. I need to sit and talk to the pygobject people about bugs that really bite us.

**Comment by slavikvin** [comment]
Thanks for explanation, i`ll follow that bug on bugzilla.
