### ISSUE TITLE
Cleanup/update LVM size calculations and expectations

### ISSUE THREAD

**Issue by vpodzime** [rhinstaller/blivet#31]
Blivet's LVM code contains many (often magic) calculations focused on free space left or required by LVM (e.g. "*How much space is this LV going to take from a disk?*" or "*How much space there will be for LVM on top of RAIDn?*"). Many of these calculations come from the lvm1 (called simply *lvm*) era and many are based on some empirical testing or just experience without any clear inspectable explanation. Also lvm2 has different size limitations than lvm1 used to have so we need to update these pieces of code/numbers too.

**Comment by bcl** [comment]
Ideally this information would be provided by lvm in some way that doesn't require reading its code.

**Comment by vpodzime** [comment]
I think we all dream this dream. But I think (and even more I hope) there are many needless calculations in Blivet that origin from some noise and misunderstandings.

**Comment by vpodzime** [comment]
Done.
