### ISSUE TITLE
document blivet's public API

### ISSUE THREAD

**Issue by dwlehman** [rhinstaller/blivet#321]
Since we're switching to a python-tailored [variation][1] on [semver][2] we need to document the full API. We talked about this already, including whether to use a blacklist or a whitelist. As I recall, we tentatively leaned toward a blacklist. As I'm writing this I'm still on the fence, as part of me thinks we should be both explicit and aggressive by specifying the full API as a whitelist.

[1]: http://docs.openstack.org/developer/pbr/semver.html
[2]: http://semver.org/spec/v2.0.0.html

**Comment by vpodzime** [comment]
AFAICT, this is being addressed in the PR #327

**Comment by vpodzime** [comment]
PR #327 is now merged.
