### ISSUE TITLE
resolve_glob() does not work correctly

### ISSUE THREAD

**Issue by M4rtinK** [rhinstaller/blivet#417]
The _resolve_glob()_ function from the **Blivet** _udev_ module seems to be only able to handle basic globs like this one:

`vd*` -> this will correctly cover `/dev/vda`, `/dev/vdb`, `/dev/vdc`, etc.

Unfortunately the function can't handle more "advanced" paths like `/dev/disk/by-id/ata-SATA_SSD*` or even just `/dev/vd*`.

**Comment by vojtechtrefny** [comment]
#450 fixed this
