### ISSUE TITLE
L10N - need information about "Unsupported %(name)s"

### ISSUE THREAD

**Issue by Jibec** [rhinstaller/blivet#486]
hi, can you please give the context of this sentence ? What are the possible values of %(name)s ? It is in blivet's project on Zanata. In branch :  rhel7-branch

thanks for your help !

Information available :
Unsupported %(name)s

#127; Refs: ../blivet/formats/disklabel.py:232

    Resource ID: e5757b8b6ae11f8c5a6edec53c1b1f1b
    Message Context: No content
    Reference: ../blivet/formats/disklabel.py:232
    Flags: python-format
    Source Comment: No content

**Comment by vojtechtrefny** [comment]
The only value for name seems to be "partition table"  (from `../blivet/formats/disklabel.py:44`).

**Comment by Jibec** [comment]
ok, adding a comment would be really helpful :) thanks for your help

**Comment by Jibec** [comment]
kind remember : can you please add a comment for translator?
