### ISSUE TITLE
L10N - Too many version in Zanata

### ISSUE THREAD

**Issue by Jibec** [rhinstaller/blivet#495]
Hi there,

can you please clean unneeded version from Zanata and tell us what is the version for F25 ? Master ?

thanks for your help

**Comment by pravins** [comment]
We are having Fedora 25 translation sprint from 3rd-9th September, it will be very useful to get this fixed before it. https://fedora.zanata.org/project/view/blivet?dswid=6683

**Comment by vojtechtrefny** [comment]
Current version of Blivet in Fedora 25 is [2.1.2](https://apps.fedoraproject.org/packages/python-blivet) so the right branch is 2.1. Too bad it isn't possible to somehow tag/label the branches in Zanata or add some description.
I'm not sure how to fix this -- most of these versions are currently maintained/in development -- but we'll try to make it easier (we could close /set as read-only/ some older branches and probably remove some branches for devel versions /not yet released/).

**Comment by pravins** [comment]
On 29 August 2016 at 17:13, Vojtech Trefny <notifications@github.com> wrote:

> Current version of Blivet in Fedora 25 is 2.1.2
> <https://apps.fedoraproject.org/packages/python-blivet> so the right
> branch is 2.1. Too bad it isn't possible to somehow tag/label the branches
> in Zanata or add some description.
> I'm not sure how to fix this -- most of these versions are currently
> maintained/in development -- but we'll try to make it easier (we could
> close /set as read-only/ some older branches and probably remove some
> branches for devel versions /not yet released/).
>
Hi Alex,

Any solution here?

Thanks,
Pravin

**Comment by dwlehman** [comment]
The Fedora 25 version of blivet uses the `2.1` branch in zanata. Is there something more being requested here?

**Comment by Jibec** [comment]
no, it's perfect thank you
