### ISSUE TITLE
wrong partition type for EFI

### ISSUE THREAD

**Issue by ignatenkobrain** [rhinstaller/blivet#538]
If I choose EFI as partition filesystem in blivet-gui or in anaconda, it sets wrong partition type..

Actual parttype: `EBD0A0A2-B9E5-4433-87C0-68B6B72699C7` (Microsoft basic data)
Expected parttype: `C12A7328-F81F-11D2-BA4B-00A0C93EC93B` (EFI System)

This prevents bootctl to work.

**Comment by vpodzime** [comment]
@vojtechtrefny weren't you fixing some issue with GUID not being set or something? Or was it @japokorn ?

**Comment by vojtechtrefny** [comment]
#539 should fix this

**Comment by vpodzime** [comment]
> #539 should fix this

Merged.
