### ISSUE TITLE
SSD awareness

### ISSUE THREAD

**Issue by dwlehman** [rhinstaller/blivet#55]
##### Motivation
SSD are increasingly common and are known to be good for some things (eg: /usr, /etc) and not so good for other things (eg: swap, /home). It would be useful if blivet could make intelligent decisions when creating storage layouts on systems that include an SSD.

##### Requirements
1. be able to differentiate SSD from spinning disks or removable flash drives
    * (optionally) also differentiate locally-attached disks from network-attached disks
2. make intelligent use of SSD when allocating partitions
    * avoid SSD: swap, /home
    * prefer SSD: /usr, /
3. (optionally) extend these concepts to factor in relative cost of local versus network-attached disks when
    allocating partitions
    * eg: avoid putting swap on networked storage

This should be confined to a couple of methods/properties in StorageDevice and some additional logic in blivet.partitioning. LVM is going to make it slightly more complicated: we might have to start specifying which PV to allocate certain LVs' extents from or even create multiple VGs.

We can also explore the possibility of adding another class for USB since they are generally slower than other local disks.

Related: [issue 19](https://github.com/rhinstaller/blivet/issues/19) (cache lv support)

**Comment by dwlehman** [comment]
@vpodzime do you need a property to identify fast -v- slow media for the lvm cache stuff, or can I defer this until after blivet-2.0?

**Comment by vpodzime** [comment]
> @vpodzime do you need a property to identify fast -v- slow media for the lvm cache stuff, or can I defer this until after blivet-2.0?

We are not going to implement any automagic decisions or algorithms related to LVM cache and SSDs any time soon so this can be deferred to until after 2.0. Right now we support manual specification of LVM cache things and there's no request for anything else.

**Comment by dwlehman** [comment]
Having pushed #485 and #499 I think we can call this complete. There are no plans (that I'm aware of) to do anything automatic regarding SSDs.
