### ISSUE TITLE
RFE: extend autopart with options to disable separate boot/swap partitions

### ISSUE THREAD

**Issue by nullr0ute** [rhinstaller/blivet#551]
from https://bugzilla.redhat.com/show_bug.cgi?id=1220866

The Fedora cloud images use the following kickstart option for disk partitioning because a boot/swap partition isn't needed or useful.

zerombr
clearpart --all
part / --size 3000 --fstype ext4

The issue is that some virtual HW needs some other options like /boot/efi for virt platforms that use uEFI boot or PrEP for POWER platforms which are handled well with autopart in an architecture independent manner.

It would be useful to have --noboot and --noswap options for the autopart option as a result. That way something like the following could be used for all architectures:

autopart --nolvm --noboot --noswap

It's also not unusual these days for installs not to want to use swap space so it's useful in general

**Comment by dwlehman** [comment]
This will also require some work in [pykickstart](https://github.com/rhinstaller/pykickstart).

**Comment by vpodzime** [comment]
@dwlehman is there anything we can do for this in *blivet*? AFAICT, it's *anaconda* creating the ``PartSpec`` objects determining what's going to be allocated/created by *blivet*.

**Comment by dwlehman** [comment]
Hmm, I guess there is nothing to do here for blivet. All of the work would be in [pykickstart](https://github.com/rhinstaller/pykickstart) (adding the new options to the `autopart` command) and [anaconda](https://github.com/rhinstaller/anaconda) (handling the options as appropriate).

**Comment by nullr0ute** [comment]
So do I need to report a new issue there, has this one been moved over, or how should this be handled?

**Comment by dwlehman** [comment]
I think you have to open new issues for pykickstart and anaconda. I'm not aware of any clone/dupe functionality in github's issues.
