### ISSUE TITLE
DiskDevice instances report no model

### ISSUE THREAD

**Issue by vpodzime** [rhinstaller/blivet#84]
Probably since the commit 73d9c995c8d46f1aa248d1ade3bbb1838653b6b0 all *DiskDevice* instances report no model since they have ``self._model`` unset and it is no longer updated from their ``self.partedDevice`` attribute. I tried looking at the udev info we get at the point where we create *DiskDevice* instances, but the model is not there and ``udev.device_get_model(info)`` returns ``None``. So I don't really have any idea how to get the model back.

**Comment by dwlehman** [comment]
I'm seeing ID_MODEL in udev, but we want more information than that. The anaconda GUI uses the ```description``` property, which used to defer to self._partedDevice.model. To match the usual information from pyparted I think we want vendor and model from /sys/block/<disk> when <disk> is an actual disk. For device-mapper and md devices I think it's already taken care of.
