### ISSUE TITLE
pvscan will fail if it is created new volume group on OS without lvm cache.

### ISSUE THREAD

**Issue by kuzhev** [rhinstaller/blivet#92]
I work with LVM with openlmi-storage which uses python-blivet.
Many tests finished successfully. But I found one moment:
CreateOrModifyVG from openlmi-storage calling blivet functions failed with some text:
"Creating volume group newvolume...
PercentComplete: 100%      
Errors: 1
CIMStatusCode: 1
ErrorSourceFormat: 0
Message: pvscan failed for /dev/sda3: running lvm pvscan --cache /dev/sda3 --config  devices { preferred_names=["^/dev/mapper/", "^/dev/md/", "^/dev/sd"] }  failed
MessageArguments: []
RecommendedActions: []"

Text with "pvscan failed ..." came from blivet.

Conditions of this moment:
a. The clear OS (not Fedora) on VBox 4.2.18.
b. I create volume group with /dev/sda1, /dev/sda3, /dev/sda3 (for example).
c. The lvm daemon is absent and lvm doesn't have the cache because I do nothing with LVM utils.
I have other tests and the test with CreateOrModifyVG and existing cache finished successfully.

Reason of this behavior is in package python-blivet-1.0.5, lvmpv.py, function create():
<..>
        try:
            DeviceFormat.create(self, **kwargs)
            # Consider use of -Z|--zero
            # -f|--force or -y|--yes may be required

            # lvm has issues with persistence of metadata, so here comes the
            # hammer...
            DeviceFormat.destroy(self, **kwargs)
            #lvm.pvscan(self.device)
            lvm.pvcreate(self.device, data_alignment=self.dataAlignment)
        except Exception:
            raise
        finally:
            #lvm.pvscan(self.device)
            pass
<..>
I commented string with lvm.pvscan(self.device) and the new volume group was created successfully.
I find new versions of blivet which contain the similar code in new versions.
But I don't test new package and in new versions find the comment with "hammer..."
Do you find some variant why I mustn't comment and have a good solution on clear system without lvm cache?

**Comment by vpodzime** [comment]
@kuzhev could you please try running ``pvscan --cache`` on some PV in you environment and then ``pvscan`` (without the ``--cache`` option) and confirm the use of the cache is the problem here? If that's the case, it looks more like a bug in the LVM tools than a bug in blivet.

**Comment by kuzhev** [comment]
Results of running pvscan with and without --cache and other arguments on the clear OS are similar with results on the unclean OS with cache (after $vgcreate newvolume /dev/sda1 /dev/dsa2 /dev/sda3 and $vgremove newvolume) except the last case - pvscan without arguments with cache case gives the small addition to the stdout:
<..>
  PV /dev/sda1         lvm2 [512,00 MiB]
  PV /dev/sda2         lvm2 [8,00 GiB]
  PV /dev/sda3         lvm2 [2,00 GiB]
  Total: 3 [10,50 GiB] / in use: 0 [0   ] / in no VG: 3 [10,50 GiB]
<..>
and 
vgcreate gives 2 variant  (yes/no) for wiping every partition by user.

I think it looks more like a bug (probably some feature) in the LVM tools and after results in stdout/stderr throw exception in the blivet code.
Thank you!

**Comment by vpodzime** [comment]
Closing as per:

> I think it looks more like a bug (probably some feature) in the LVM tools and after results in stdout/stderr throw exception in the blivet code.
